// sizeGuides.js
export const SIZE_GUIDES = {
    midDress: {
      title: "Mid Dress Size Guide",
      measurements: ["Size", "Bust", "Waist", "Hip", "Length"],
      rows: [
        ["XS", 32, 24, 34, 40],
        ["S", 34, 26, 36, 41],
        ["M", 36, 28, 38, 42],
        ["L", 38, 30, 40, 43],
        ["XL", 40, 32, 42, 44],
      ],
      guideText: "Measuring Mid Dress Size",
      steps: [
        ["Bust", "Measure around fullest part of bust."],
        ["Waist", "Measure around natural waistline."],
        ["Hip", "Measure around widest part of hips."],
        ["Length", "Measure from shoulder to hem."],
      ],
    },
    sets: {
      title: "Sets Size Guide",
      measurements: ["Size", "Bust", "Waist", "Hip"],
      rows: [
        ["XS", 32, 24, 34],
        ["S", 34, 26, 36],
        ["M", 36, 28, 38],
        ["L", 38, 30, 40],
        ["XL", 40, 32, 42],
      ],
      guideText: "Measuring Set Size",
      steps: [
        ["Bust", "Measure around the fullest part of your bust."],
        ["Waist", "Measure around natural waistline."],
        ["Hip", "Measure around widest part of hips."],
      ],
    },
    pants: {
      title: "Pants Size Guide",
      measurements: ["Size", "Waist", "Hip", "Inseam"],
      rows: [
        ["28", 28, 35, 30],
        ["30", 30, 37, 31],
        ["32", 32, 39, 32],
        ["34", 34, 41, 33],
        ["36", 36, 43, 34],
      ],
      guideText: "Measuring Pants Size",
      steps: [
        ["Waist", "Measure around your natural waistline."],
        ["Hip", "Measure around the fullest part of your hips."],
        ["Inseam", "Measure from the crotch to ankle."],
      ],
    },
    casualPants: {
      title: "Casual Pants Size Guide",
      measurements: ["Size", "Waist", "Hip", "Inseam"],
      rows: [
        ["28", 28, 35, 30],
        ["30", 30, 37, 31],
        ["32", 32, 39, 32],
        ["34", 34, 41, 33],
        ["36", 36, 43, 34],
      ],
      guideText: "Measuring Casual Pants Size",
      steps: [
        ["Waist", "Measure around your natural waistline."],
        ["Hip", "Measure around the fullest part of your hips."],
        ["Inseam", "Measure from the crotch to ankle."],
      ],
    },
    top: {
      title: "Top Size Guide",
      measurements: ["Size", "Bust", "Length", "Shoulder"],
      rows: [
        ["XS", 32, 23, 14],
        ["S", 34, 24, 15],
        ["M", 36, 25, 16],
        ["L", 38, 26, 17],
        ["XL", 40, 27, 18],
      ],
      guideText: "Measuring Top Size",
      steps: [
        ["Bust", "Measure around the fullest part of your bust."],
        ["Length", "Measure from shoulder top to bottom hem."],
        ["Shoulder", "Measure edge to edge across shoulders."],
      ],
    },
    sleepWear: {
      title: "Sleepwear Size Guide",
      measurements: ["Size", "Bust", "Waist", "Hip"],
      rows: [
        ["XS", 32, 24, 34],
        ["S", 34, 26, 36],
        ["M", 36, 28, 38],
        ["L", 38, 30, 40],
        ["XL", 40, 32, 42],
      ],
      guideText: "Measuring Sleepwear Size",
      steps: [
        ["Bust", "Measure around the fullest part of your bust."],
        ["Waist", "Measure around natural waistline."],
        ["Hip", "Measure around widest part of hips."],
      ],
    },
    shorts: {
      title: "Shorts Size Guide",
      measurements: ["Size", "Waist", "Hip", "Length"],
      rows: [
        ["XS", 24, 34, 12],
        ["S", 26, 36, 13],
        ["M", 28, 38, 14],
        ["L", 30, 40, 15],
        ["XL", 32, 42, 16],
      ],
      guideText: "Measuring Shorts Size",
      steps: [
        ["Waist", "Measure around waist."],
        ["Hip", "Measure around the widest part of hips."],
        ["Length", "Measure from waist to bottom hem."],
      ],
    },
    blazers: {
      title: "Blazer Size Guide",
      measurements: ["Size", "Chest", "Waist", "Shoulder", "Length"],
      rows: [
        ["36", 36, 30, 17, 27],
        ["38", 38, 32, 18, 28],
        ["40", 40, 34, 19, 29],
        ["42", 42, 36, 20, 30],
        ["44", 44, 38, 21, 31],
      ],
      guideText: "Measuring Blazer Size",
      steps: [
        ["Chest", "Measure around the fullest part of your chest."],
        ["Waist", "Measure around natural waistline."],
        ["Shoulder", "Measure edge to edge."],
        ["Length", "Measure from shoulder top to blazer bottom."],
      ],
    },
    longDress: {
      title: "Long Dress Size Guide",
      measurements: ["Size", "Bust", "Waist", "Hip", "Length"],
      rows: [
        ["XS", 32, 24, 34, 50],
        ["S", 34, 26, 36, 51],
        ["M", 36, 28, 38, 52],
        ["L", 38, 30, 40, 53],
        ["XL", 40, 32, 42, 54],
      ],
      guideText: "Measuring Long Dress Size",
      steps: [
        ["Bust", "Measure around fullest part of bust."],
        ["Waist", "Measure around natural waistline."],
        ["Hip", "Measure around widest part of hips."],
        ["Length", "Measure from shoulder to bottom hem."],
      ],
    },
    skirt: {
      title: "Skirt Size Guide",
      measurements: ["Size", "Waist", "Hip", "Length"],
      rows: [
        ["XS", 24, 34, 18],
        ["S", 26, 36, 19],
        ["M", 28, 38, 20],
        ["L", 30, 40, 21],
        ["XL", 32, 42, 22],
      ],
      guideText: "Measuring Skirt Size",
      steps: [
        ["Waist", "Measure around waist."],
        ["Hip", "Measure around widest part of hips."],
        ["Length", "Measure vertically from waist to hem."],
      ],
    },
    suits: {
      title: "Suit Size Guide",
      measurements: ["Size", "Chest", "Waist", "Shoulder", "Inseam"],
      rows: [
        ["36", 36, 30, 17, 30],
        ["38", 38, 32, 18, 31],
        ["40", 40, 34, 19, 32],
        ["42", 42, 36, 20, 33],
        ["44", 44, 38, 21, 34],
      ],
      guideText: "Measuring Suit Size",
      steps: [
        ["Chest", "Measure around fullest part of chest."],
        ["Waist", "Measure around natural waistline."],
        ["Shoulder", "Measure edge to edge."],
        ["Inseam", "Measure inside leg from crotch to ankle."],
      ],
    },
    shirts: {
      title: "Shirt Size Guide",
      measurements: ["Size", "Chest", "Shoulder", "Length", "Sleeve Length"],
      rows: [
        ["S", 38, 17, 28, 24],
        ["M", 40, 18, 29, 25],
        ["L", 42, 19, 30, 26],
        ["XL", 44, 20, 31, 27],
        ["XXL", 46, 21, 32, 28],
      ],
      guideText: "Measuring Shirt Size",
      steps: [
        ["Chest", "Measure around fullest part of chest."],
        ["Shoulder", "Measure edge to edge."],
        ["Length", "Measure from shoulder to hem."],
        ["Sleeve Length", "Measure from shoulder seam to cuff."],
      ],
    },
    kidsShirts: {
      title: "Kids Shirt Size Guide",
      measurements: ["Size", "Chest", "Length"],
      rows: [
        ["2-3Y", 22, 15],
        ["4-5Y", 24, 17],
        ["6-7Y", 26, 19],
        ["8-9Y", 28, 21],
        ["10-11Y", 30, 23],
      ],
      guideText: "Measuring Kids Shirt Size",
      steps: [
        ["Chest", "Measure around chest."],
        ["Length", "Measure shoulder to hem."],
      ],
    },
    kidsPants: {
      title: "Kids Pants Size Guide",
      measurements: ["Size", "Waist", "Inseam"],
      rows: [
        ["2-3Y", 20, 14],
        ["4-5Y", 21, 16],
        ["6-7Y", 22, 18],
        ["8-9Y", 24, 20],
        ["10-11Y", 26, 22],
      ],
      guideText: "Measuring Kids Pants Size",
      steps: [
        ["Waist", "Measure around waist."],
        ["Inseam", "Measure inside leg from crotch to ankle."],
      ],
    },
    kidsShorts: {
      title: "Kids Shorts Size Guide",
      measurements: ["Size", "Waist", "Length"],
      rows: [
        ["2-3Y", 20, 10],
        ["4-5Y", 21, 11],
        ["6-7Y", 22, 12],
        ["8-9Y", 24, 13],
        ["10-11Y", 26, 14],
      ],
      guideText: "Measuring Kids Shorts Size",
      steps: [
        ["Waist", "Measure around waist."],
        ["Length", "Measure from waist to hem."],
      ],
    },
    kidsSleepWear: {
      title: "Kids Sleepwear Size Guide",
      measurements: ["Size", "Chest", "Waist", "Length"],
      rows: [
        ["2-3Y", 22, 20, 22],
        ["4-5Y", 24, 22, 24],
        ["6-7Y", 26, 24, 26],
        ["8-9Y", 28, 26, 28],
        ["10-11Y", 30, 28, 30],
      ],
      guideText: "Measuring Kids Sleepwear Size",
      steps: [
        ["Chest", "Measure around chest."],
        ["Waist", "Measure around waist."],
        ["Length", "Measure shoulder to hem."],
      ],
    },
    kidsSets: {
      title: "Kids Sets Size Guide",
      measurements: ["Size", "Chest", "Waist", "Hip"],
      rows: [
        ["2-3Y", 22, 20, 24],
        ["4-5Y", 24, 22, 26],
        ["6-7Y", 26, 24, 28],
        ["8-9Y", 28, 26, 30],
        ["10-11Y", 30, 28, 32],
      ],
      guideText: "Measuring Kids Set Size",
      steps: [
        ["Chest", "Measure around chest."],
        ["Waist", "Measure around waist."],
        ["Hip", "Measure around hips."],
      ],
    },
  };
  